### ISSUE TITLE
Great bug hunt

### ISSUE THREAD

**Issue by antonrufino** [antonrufino/Young-Blood-Exer-3-Library-Information-System#15]
A lot of features have been implemented but untested, as seen in pull request #14.  
As such we need to fix bugs before midnight in order to finish this. Post all bugs here and close relevant issues when appropriate.

**Comment by antonrufino** [comment]
Marami pa naman sa nakita ko ay mga UI issues pa lang naman.

**Comment by chacychavez** [comment]
Di ko masyadong pinakialaman ung UI kaya ganyan.

**Comment by antonrufino** [comment]
Let's move this discussion to the pull request... ._.

**Comment by antonrufino** [comment]
ok here we go

**Comment by antonrufino** [comment]
nakita ko naman sa commits na di ginalaw yun ui. habang inaayos ui try mo magtest ng functionality
